# Autogenerated by build.c
set(CAKE_SOURCES  token.c  hash.c  hashmap.c  console.c  tokenizer.c  osstream.c  fs.c  options.c  expressions.c  pre_expressions.c  flow_object.c  parser.c  visit.c  flow_visit.c  error.c  format_visit.c  type.c )
set(CAKE_HEADERS  console.h  tokenizer.h  parser.h  error.h  fs.h  hash.h  flow_object.h  hashmap.h  osstream.h  options.h  token.h  type.h  pre_expressions.h  expressions.h  visit.h  format_visit.h )
set(HOEDOWN_SOURCE_NAMES  autolink.c buffer.c document.c escape.c hoedown.c html.c html_blocks.c html_smartypants.c stack.c version.c)
set(HOEDOWN_SOURCES )
foreach(src ${HOEDOWN_SOURCE_NAMES})
  list(APPEND HOEDOWN_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/tools/hoedown/${src}")
endforeach()
unset(CAKE_SOURCE_NAMES)
